Tiryoh/docker-ros2-desktop-vnc

README.md
=> docs: Update the execution command

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md, foxy/Dockerfile, foxy/ros-foxy-desktop.sh
Foxy depends on Gazebo 11
https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023
=> feat: Add ROS 2 Foxy

foxy/ros-foxy-desktop.sh
`ros-foxy-gazebo-ros-pkgs` is ready.
https://github.com/ros/rosdistro/pull/25595
=> feat: Enable ros-foxy-gazebo-ros-pkgs

.github/workflows/deploy.yml, .github/workflows/test.yml, dashing/Dockerfile, dashing/ros-dashing-desktop.sh, eloquent/Dockerfile, eloquent/ros-eloquent-desktop.sh
=> feat: Add install scripts

dashing/ros-dashing-desktop.sh
=> fix: Fix dashing tag image

.github/workflows/deploy.yml
This is a temporary fix for #12.
=> chore: Publish to ghcr.io

.github/workflows/deploy.yml, .github/workflows/test.yml, foxy-arm64/Dockerfile, foxy-arm64/ros-foxy-desktop.sh
=> feat: Add Dockerfile for foxy-arm64 to support Apple Silicon

README.md
Thank you so much for publishing an awesome work!
It is a pretty fix :D
=> fix the link to Foxy's Dockerfile

.github/workflows/deploy.yml, README.md
ROS 2 Dashing has been deprecated in May 2021
=> feat: Set foxy as the "latest" image

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md
=> ci: Add ROS 2 Galactic

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md
=> feat: Drop ROS 2 Dashing support

CHANGELOG.md
=> release: v1.2.0

.github/workflows/deploy.yml, .github/workflows/test.yml, galactic-arm64/Dockerfile, galactic-arm64/ros-galactic-desktop.sh
=> feat: Add Dockerfile for galactic-arm64 to support Apple Silicon

.github/workflows/deploy.yml
```
$ docker inspect tiryoh/ros2-desktop-vnc:foxy | jq ".[0].Config.Labels"
{
"maintainer": "Tiryoh<*****@gmail.com>",
"org.opencontainers.image.created": "2022-01-16T09:34:17.340Z",
"org.opencontainers.image.description": "Dockerfiles to provide HTML5 VNC interface to access Ubuntu LXDE + ROS2",
"org.opencontainers.image.licenses": "Apache-2.0",
"org.opencontainers.image.revision": "d18f594c61363fefaf088d79d91b24006d9e41a7",
"org.opencontainers.image.source": "https://github.com/Tiryoh/docker-ros2-desktop-vnc",
"org.opencontainers.image.title": "docker-ros2-desktop-vnc",
"org.opencontainers.image.url": "https://github.com/Tiryoh/docker-ros2-desktop-vnc",
"org.opencontainers.image.version": "foxy-arm64-20220116T0934"
}
```
=> chore: Add docker label

.github/workflows/deploy.yml, .github/workflows/test.yml, rolling-arm64/Dockerfile, rolling/Dockerfile
=> feat: Add ROS 2 Rolling Ridley

.github/workflows/deploy.yml, .github/workflows/test.yml
https://stackoverflow.com/questions/70830094/marking-github-actions-workflow-as-failed-if-a-single-job-fails-in-matrix
=> ci: Allow execution even if other jobs fail

.github/workflows/deploy.yml, .github/workflows/test.yml
=> fix: Fix platform specifying error

foxy-arm64/Dockerfile, foxy/Dockerfile, galactic-arm64/Dockerfile, galactic/Dockerfile, humble-arm64/Dockerfile, humble/Dockerfile, rolling-arm64/Dockerfile, rolling/Dockerfile
=> feat: Enable bash-completion

foxy/Dockerfile
https://github.com/Tiryoh/docker-ros2-desktop-vnc/issues/87#issuecomment-1537485200
=> fix: Stop using mirror server

.github/workflows/deploy.yml, .github/workflows/test.yml, README.md, iron-arm64/Dockerfile, iron/Dockerfile
ros_gz, ros_ign are not ready
https://repo.ros2.org/status_page/ros_iron_default.html?q=ros_gz
=> feat: Add ROS 2 Iron Irwini

foxy/entrypoint.sh, humble/entrypoint.sh, iron/entrypoint.sh, rolling/entrypoint.sh
=> feat: Add terminator shortcut on desktop

.github/workflows/test.yml, foxy/Dockerfile, foxy/entrypoint.sh, humble/Dockerfile, humble/entrypoint.sh, iron/Dockerfile, iron/entrypoint.sh, rolling/Dockerfile, rolling/entrypoint.sh
=> feat: Add VSCodium

.github/actions/deploy/action.yml
fix https://github.com/Tiryoh/docker-ros2-desktop-vnc/pull/111
=> chore: Fix "no space left on device"

foxy/Dockerfile, humble/Dockerfile, iron/Dockerfile, rolling/Dockerfile
=> change sign and repo to vscodium

.coderabbit.yaml, .gemini/config.yaml
This project is maintained individually, and since there are numerous bot-generated PRs, I'm disabling automatic reviews.
=> chore: Add initial configuration for CodeRabbit and Gemini Code Assist
